SRC_F	=	main					\
			draw/d_math				\
			draw/d_draw				\
			draw/d_fps				\
			draw/d_render			\
			draw/d_shadow			\
			memory/m_free			\
			memory/m_utils			\
			minimap/n_draw			\
			minimap/n_draw_utils	\
			minimap/n_grid			\
			minimap/n_minimap		\
			minimap/n_player		\
			minimap/n_utils			\
			mouse/o_buttons			\
			mouse/o_init			\
			mouse/o_mouse			\
			parsing/p_color			\
			parsing/p_color_utils	\
			parsing/p_file			\
			parsing/p_map			\
			parsing/p_map_check		\
			parsing/p_flood_fill	\
			parsing/p_map_utils		\
			parsing/p_texture		\
			parsing/p_validation	\
			player/l_init			\
			player/l_mlx			\
			player/l_move			\
			raycasting/r_dda		\
			raycasting/r_init		\
			raycasting/r_math		\
			raycasting/r_ray		\
			texture/t_texture		\
			utils/u_path			\
			utils/u_texture
