SRC_F	=	main						\
			draw/d_math					\
			draw/d_draw					\
			draw/d_fps					\
			draw/d_render				\
			draw/d_shadow				\
			memory/m_free				\
			memory/m_utils				\
			minimap_bonus/n_draw		\
			minimap_bonus/n_draw_utils	\
			minimap_bonus/n_grid		\
			minimap_bonus/n_minimap		\
			minimap_bonus/n_player		\
			minimap_bonus/n_utils		\
			mouse_bonus/o_buttons		\
			mouse_bonus/o_init			\
			mouse_bonus/o_mouse			\
			parsing/p_color				\
			parsing/p_color_utils		\
			parsing/p_file				\
			parsing/p_map				\
			parsing/p_map_check			\
			parsing/p_flood_fill		\
			parsing/p_map_utils			\
			parsing/p_texture			\
			parsing/p_validation		\
			player/l_init				\
			player/l_mlx				\
			player/l_move				\
			raycasting/r_horizontal		\
			raycasting/r_raycasting		\
			raycasting/r_vertical		\
			raycasting/r_utils			\
			texture/t_texture			\
			utils/u_path				\
			utils/u_texture
